{% set name = "lisaconstants" %}
{% set version = "1.3.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.in2p3.fr/lisa-simulation/constants/-/archive/v{{ version }}/constants-v{{ version }}.tar.gz
  sha256: 52dc0bc041286d12ef0a8263eee45ba3a0c8adf37bac1cc54d447b8959d532bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION_FOR_LISACONSTANTS={{ version }}

requirements:
  host:
    - python {{ python_min }} 
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - jinja2

test:
  source_files:
    - tests/test_cheader.py
    - tests/test_constants.py
  imports:
    - lisaconstants
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  commands:
    - pip check
    - python -m pytest tests/test_cheader.py
    - python -m pytest tests/test_constants.py

about:
  home: https://gitlab.in2p3.fr/lisa-simulation/constants
  summary: 'Provides physical constants and LISA mission parameters sanctioned by the LISA Consortium'
  description: |
    LISA Constants is a Python package providing values sanctioned by the LISA
    Consortium for physical constants and mission parameters. LISA Constants is
    intended to be consistently used by other pieces of software related to the
    simulation of the instrument, of gravitational wave signals, and others.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://lisa-simulation.pages.in2p3.fr/constants/latest
  dev_url: https://gitlab.in2p3.fr/lisa-simulation/constants

extra:
  recipe-maintainers:
    - j2bbayle
    - mpigou
